/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Tisha
 */
public class Memebership extends javax.swing.JFrame {

    /**
     * Creates new form Memebership
     */
    public Memebership() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();
        ADD_MEMBER = new javax.swing.JButton();
        Delete_member = new javax.swing.JButton();
        find_member = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setMaximumSize(new java.awt.Dimension(600, 600));
        getContentPane().setLayout(null);

        ADD_MEMBER.setText("Add yourself as a member");
        ADD_MEMBER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADD_MEMBERActionPerformed(evt);
            }
        });
        getContentPane().add(ADD_MEMBER);
        ADD_MEMBER.setBounds(100, 24, 210, 52);

        Delete_member.setText("Cancel Membership");
        Delete_member.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_memberActionPerformed(evt);
            }
        });
        getContentPane().add(Delete_member);
        Delete_member.setBounds(100, 94, 210, 48);

        find_member.setText("Edit information");
        find_member.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                find_memberActionPerformed(evt);
            }
        });
        getContentPane().add(find_member);
        find_member.setBounds(100, 160, 210, 42);

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(20, 253, 90, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ADD_MEMBERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADD_MEMBERActionPerformed
         this.setVisible(false);
         Addmember a=new Addmember();
         a.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_ADD_MEMBERActionPerformed

    private void Delete_memberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_memberActionPerformed
         this.setVisible(false);
         Deletemember d=new Deletemember();
         d.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_Delete_memberActionPerformed

    private void find_memberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_find_memberActionPerformed
        this.setVisible(false);
        Findmember f=new Findmember();
        f.setVisible(true);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_find_memberActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         this.setVisible(true);
         // mo=new Menu();
        // mo.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Memebership.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Memebership.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Memebership.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Memebership.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Memebership().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADD_MEMBER;
    private javax.swing.JButton Delete_member;
    private javax.swing.JButton find_member;
    private javax.swing.JButton jButton1;
    private javax.swing.JColorChooser jColorChooser1;
    // End of variables declaration//GEN-END:variables
}
